### ISSUE TITLE
suggested documentation improvement

### ISSUE THREAD

**Issue by sydb** [wendellpiez/XMLjellysandwich#3]
Here is a suggestion for updating a particular section of the README markdown file. Since it is written in gfmd, it will show up on this ticket rendered. But I believe if you copy-and-paste (or edit the ticket) you can access the markdown. I have inserted questions surrounded by guillemets in bold.

#### ‘hosting’ (HTML) page

The HTML (or XHTML) ‘hosting’ file is the landing page that is loaded into the user’s browser to kick everything else off. You can create one by copying and then altering any one of the `index.html` files from one of the `docs/*/` directories of this repository, or by using the “starter maker” XSLT program described [below](#starter-xslt-maker).

Either way, the ‘hosting’ HTML page needs a few control points:

- There should be a `script[@src='lib/saxon/SaxonJS.min.js']`, or equivalent. The named Javascript file must be in the location mentioned

```
<script type="text/javascript"
        src="../lib/saxon/SaxonJS.min.js"><!-- cosmetic comment --></script>
```

- Within a second `script` element the SaxonJS.transform() function should be set up with settings for your source XML and your SEF (compiled XSLT).  In the example below `{$resource_filename}` should be the path to the XML file you plan to deliver. **&#xAB;?wp is path relative from the hosting file or the .sef file?&#xBB;** The `{$transform_href}` should point to your your SEF. **&#xAB;?wp same Q?&#xBB;** The `{$xmljellysandwich_pack}` identifies the entry point for the stylesheet (this names a template appearing in XSLTs produced by the starter-maker, but your XSLT could offer its own entry points). Adjust as necessary for your XSLT.

```
<script>
    window.onload = function() {
    SaxonJS.transform({
        sourceLocation:     "{$resource_filename}",
        stylesheetLocation: "{$transform_href}",
        initialTemplate:    "xmljellysandwich_pack"
    });
    }     
</script>
```
 - Either on the `<body>` element of the HTML, or somewhere inside it, make sure to put in a dummy element that has an `@id` attribute. This dummy element will be replaced with whatever the SEFed stylesheet writes to that ID using `<xsl:result-document>`. The hostHTMLfile-maker.xsl program (described [below](#host-html-file-maker)) uses the IDs “header”, “directory”, “body”, and “footer”, each prefixed with “xmljellysandwich_”.  These dummy elements (which could be just one element, the entire `<body>`, if you like) will be replaced by a `<xsl:result-document>` instruction in the XSLT-turned-SEF.”.

Note that these and many other runtime options for SaxonJS are documented at http://www.saxonica.com/saxon-js/documentation/index.html#!api/transform.

You are done with the host file. (You can come back.)

**Comment by wendellpiez** [comment]
Thanks @sydb
